D1:
 x2v_interleave_local:
  dataset_type: text2image_general
  raw_bytes_input: true
  is_image: true
  target_modality: "image"
  text_template: true
  task_type: "t2v"
  dataset_names:
    local_100:
      data_dir:
        - datasets/text2imgae/local_256.parquet
  debug_parquet_repeat: 256  # debug option for quick smoke tests on small local datasets

  video_transform_args:
    resolution: 768
    mode: "bucket"
    divisible_crop_size: 16
    aspect_ratios: ["21:9", "16:9", "4:3", "1:1", "3:4", "9:16"]
    mean: 0.5
    std: 0.5

  is_mandatory: false
  weight: 1.0
  caption_key: "caption"
